# FX parameters raw config without function calls
FX_PARAMS_DATA = {
    "BR": {
        "cc_msb": "78",
        "nrpn_lsb": "1",
        "nrpn_msb": "5",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
    "OVER": {
        "cc_msb": "81",
        "nrpn_lsb": "1",
        "nrpn_msb": "8",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
    "SRR": {
        "cc_msb": "79",
        "nrpn_lsb": "1",
        "nrpn_msb": "6",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
    "SR.RT(pre/post)": {
        "cc_msb": "80",
        "nrpn_lsb": "1",
        "nrpn_msb": "7",
        "max_midi": 1,
        "min_midi": 0,
        "max_val": 1,
        "min_val": 0,
        "default": "pre",
        "options": ["pre", "post"],
    },
    "OD.RT(pre/post)": {
        "cc_msb": "82",
        "nrpn_lsb": "1",
        "nrpn_msb": "9",
        "max_midi": 1,
        "min_midi": 0,
        "max_val": 1,
        "min_val": 0,
        "default": "pre",
        "options": ["pre", "post"],
    },
    "DEL": {
        "cc_msb": "30",
        "nrpn_lsb": "1",
        "nrpn_msb": "36",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
    "REV": {
        "cc_msb": "31",
        "nrpn_lsb": "1",
        "nrpn_msb": "37",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
    "CHR": {
        "cc_msb": "29",
        "nrpn_lsb": "1",
        "nrpn_msb": "35",
        "max_midi": 127,
        "min_midi": 0,
        "max_val": 127,
        "min_val": 0,
        "default": 0,
    },
}
