"""Filter toolset for Moog Sub 37 synthesizer."""

from pydantic_ai.toolsets import FunctionToolset

from synthgenie.synthesizers.sub37.tools.filter_tool import (
    set_filter_cutoff,
    set_filter_cutoff_nrpn,
    set_filter_drive_nrpn,
    set_filter_eg_amt,
    set_filter_eg_amt_nrpn,
    set_filter_eg_attack_exp_nrpn,
    set_filter_eg_attack_nrpn,
    set_filter_eg_attack_time,
    set_filter_eg_clk_div_nrpn,
    set_filter_eg_decay_nrpn,
    set_filter_eg_decay_time,
    set_filter_eg_delay,
    set_filter_eg_delay_nrpn,
    set_filter_eg_hold_nrpn,
    set_filter_eg_kb_amt,
    set_filter_eg_kb_track_nrpn,
    set_filter_eg_latch_nrpn,
    set_filter_eg_loop_nrpn,
    set_filter_eg_multi_trig_cc,
    set_filter_eg_multi_trig_nrpn,
    set_filter_eg_release_nrpn,
    set_filter_eg_release_time,
    set_filter_eg_reset,
    set_filter_eg_reset_nrpn,
    set_filter_eg_sustain_level,
    set_filter_eg_sustain_nrpn,
    set_filter_eg_sync_nrpn,
    set_filter_eg_vel_amt,
    set_filter_eg_vel_amt_nrpn,
    set_filter_kb_amt,
    set_filter_kb_amt_nrpn,
    set_filter_multidrive,
    set_filter_resonance,
    set_filter_resonance_nrpn,
    set_filter_slope_nrpn,
    set_filter_slopes_cc,
)

# Create filter toolset with all tools
filter_toolset = FunctionToolset(
    tools=[
        set_filter_cutoff,
        set_filter_cutoff_nrpn,
        set_filter_drive_nrpn,
        set_filter_eg_amt,
        set_filter_eg_amt_nrpn,
        set_filter_eg_attack_exp_nrpn,
        set_filter_eg_attack_nrpn,
        set_filter_eg_attack_time,
        set_filter_eg_clk_div_nrpn,
        set_filter_eg_decay_nrpn,
        set_filter_eg_decay_time,
        set_filter_eg_delay,
        set_filter_eg_delay_nrpn,
        set_filter_eg_hold_nrpn,
        set_filter_eg_kb_amt,
        set_filter_eg_kb_track_nrpn,
        set_filter_eg_latch_nrpn,
        set_filter_eg_loop_nrpn,
        set_filter_eg_multi_trig_cc,
        set_filter_eg_multi_trig_nrpn,
        set_filter_eg_release_nrpn,
        set_filter_eg_release_time,
        set_filter_eg_reset,
        set_filter_eg_reset_nrpn,
        set_filter_eg_sustain_level,
        set_filter_eg_sustain_nrpn,
        set_filter_eg_sync_nrpn,
        set_filter_eg_vel_amt,
        set_filter_eg_vel_amt_nrpn,
        set_filter_kb_amt,
        set_filter_kb_amt_nrpn,
        set_filter_multidrive,
        set_filter_resonance,
        set_filter_resonance_nrpn,
        set_filter_slope_nrpn,
        set_filter_slopes_cc,
    ]
)


# Keywords that suggest using filter tools
FILTER_KEYWORDS = {
    'filter',
    'cutoff',
    'frequency',
    'resonance',
    'q',
    'bright',
    'brighter',
    'dark',
    'darker',
    'muffled',
    'sharp',
    'dull',
    'sweep',
    'swoosh',
    'low pass',
    'lowpass',
    'drive',
    'overdrive',
    'distortion',
    'grit',
    'slope',
    'rolloff',
    'envelope',
    'attack',
    'decay',
    'sustain',
    'release',
    'adsr',
    'keyboard tracking',
    'vel',
    'velocity',
    'modulation',
    'mod amount',
    'filter eg',
    'filter envelope',
}
