"""Modulation toolset for Moog Sub 37 synthesizer."""

from pydantic_ai.toolsets import FunctionToolset

from synthgenie.synthesizers.sub37.tools.lfo_tool import (
    set_lfo1_clk_div_nrpn,
    set_lfo1_clk_src_nrpn,
    set_lfo1_kb_reset_cc,
    set_lfo1_kb_reset_nrpn,
    set_lfo1_kb_track_nrpn,
    set_lfo1_range_cc,
    set_lfo1_range_nrpn,
    set_lfo1_rate_high_res,
    set_lfo1_rate_nrpn,
    set_lfo1_sync_nrpn,
    set_lfo2_clk_div_nrpn,
    set_lfo2_clk_src_nrpn,
    set_lfo2_kb_reset_cc,
    set_lfo2_kb_reset_nrpn,
    set_lfo2_kb_track_nrpn,
    set_lfo2_range_cc,
    set_lfo2_range_nrpn,
    set_lfo2_rate_high_res,
    set_lfo2_rate_nrpn,
    set_lfo2_sync_nrpn,
)
from synthgenie.synthesizers.sub37.tools.mod_tool import (
    set_mod1_ctl4_amt_nrpn,
    set_mod1_dest_cc,
    set_mod1_dest_nrpn,
    set_mod1_filter_amt_cc,
    set_mod1_filter_amt_nrpn,
    set_mod1_mwhl_amt_nrpn,
    set_mod1_osc_1_2_sel_cc,
    set_mod1_pgm_amt_nrpn,
    set_mod1_pgm_dest_amt_cc,
    set_mod1_pgm_dest_nrpn,
    set_mod1_pgm_src_nrpn,
    set_mod1_pitch_amt_cc,
    set_mod1_pitch_dest_nrpn,
    set_mod1_pressure_amt_nrpn,
    set_mod1_source_cc,
    set_mod1_source_nrpn,
    set_mod1_velocity_amt_nrpn,
    set_mod2_ctl4_amt_nrpn,
    set_mod2_dest_cc,
    set_mod2_dest_nrpn,
    set_mod2_filter_amt_cc,
    set_mod2_filter_amt_nrpn,
    set_mod2_mwhl_amt_nrpn,
    set_mod2_osc_1_2_sel_cc,
    set_mod2_pgm_amt_nrpn,
    set_mod2_pgm_dest_amt_high_res,
    set_mod2_pgm_dest_nrpn,
    set_mod2_pgm_src_nrpn,
    set_mod2_pitch_amt_cc,
    set_mod2_pitch_amt_nrpn,
    set_mod2_pitch_dest_nrpn,
    set_mod2_pressure_amt_nrpn,
    set_mod2_source_cc,
    set_mod2_source_nrpn,
    set_mod2_velocity_amt_nrpn,
    set_mod_wheel_high_res,
)

# Create modulation toolset with all tools
modulation_toolset = FunctionToolset(
    tools=[
        # LFO tools
        set_lfo1_clk_div_nrpn,
        set_lfo1_clk_src_nrpn,
        set_lfo1_kb_reset_cc,
        set_lfo1_kb_reset_nrpn,
        set_lfo1_kb_track_nrpn,
        set_lfo1_range_cc,
        set_lfo1_range_nrpn,
        set_lfo1_rate_high_res,
        set_lfo1_rate_nrpn,
        set_lfo1_sync_nrpn,
        set_lfo2_clk_div_nrpn,
        set_lfo2_clk_src_nrpn,
        set_lfo2_kb_reset_cc,
        set_lfo2_kb_reset_nrpn,
        set_lfo2_kb_track_nrpn,
        set_lfo2_range_cc,
        set_lfo2_range_nrpn,
        set_lfo2_rate_high_res,
        set_lfo2_rate_nrpn,
        set_lfo2_sync_nrpn,
        # Modulation routing tools
        set_mod1_ctl4_amt_nrpn,
        set_mod1_dest_cc,
        set_mod1_dest_nrpn,
        set_mod1_filter_amt_cc,
        set_mod1_filter_amt_nrpn,
        set_mod1_mwhl_amt_nrpn,
        set_mod1_osc_1_2_sel_cc,
        set_mod1_pgm_amt_nrpn,
        set_mod1_pgm_dest_amt_cc,
        set_mod1_pgm_dest_nrpn,
        set_mod1_pgm_src_nrpn,
        set_mod1_pitch_amt_cc,
        set_mod1_pitch_dest_nrpn,
        set_mod1_pressure_amt_nrpn,
        set_mod1_source_cc,
        set_mod1_source_nrpn,
        set_mod1_velocity_amt_nrpn,
        set_mod2_ctl4_amt_nrpn,
        set_mod2_dest_cc,
        set_mod2_dest_nrpn,
        set_mod2_filter_amt_cc,
        set_mod2_filter_amt_nrpn,
        set_mod2_mwhl_amt_nrpn,
        set_mod2_osc_1_2_sel_cc,
        set_mod2_pgm_amt_nrpn,
        set_mod2_pgm_dest_amt_high_res,
        set_mod2_pgm_dest_nrpn,
        set_mod2_pgm_src_nrpn,
        set_mod2_pitch_amt_cc,
        set_mod2_pitch_amt_nrpn,
        set_mod2_pitch_dest_nrpn,
        set_mod2_pressure_amt_nrpn,
        set_mod2_source_cc,
        set_mod2_source_nrpn,
        set_mod2_velocity_amt_nrpn,
        set_mod_wheel_high_res,
    ]
)


# Keywords that suggest using modulation tools
MODULATION_KEYWORDS = {
    'lfo',
    'modulation',
    'mod',
    'vibrato',
    'tremolo',
    'wobble',
    'sweep',
    'cycling',
    'rhythmic',
    'pulsing',
    'rate',
    'speed',
    'depth',
    'amount',
    'sync',
    'tempo',
    'clock',
    'mod wheel',
    'modwheel',
    'wheel',
    'velocity',
    'pressure',
    'aftertouch',
    'controller',
    'expression',
    'dynamic',
    'movement',
    'automation',
    'routing',
    'source',
    'destination',
    'target',
    'assign',
    'keyboard tracking',
    'track',
}
