"""Oscillator toolset for Moog Sub 37 synthesizer."""

from pydantic_ai.toolsets import FunctionToolset

from synthgenie.synthesizers.sub37.tools.osc_tool import (
    set_fb_ext_on_nrpn,
    set_feedback_ext_level_cc,
    set_feedback_ext_level_nrpn,
    set_noise_level_cc,
    set_noise_level_nrpn,
    set_noise_on_nrpn,
    set_osc1_level_cc,
    set_osc1_level_nrpn,
    set_osc1_octave_cc,
    set_osc1_octave_nrpn,
    set_osc1_on_nrpn,
    set_osc1_wave_high_res,
    set_osc1_wave_nrpn,
    set_osc2_beat_freq_high_res,
    set_osc2_beat_nrpn,
    set_osc2_freq_high_res,
    set_osc2_freq_nrpn,
    set_osc2_hard_sync_cc,
    set_osc2_hard_sync_nrpn,
    set_osc2_kb_ctrl_nrpn,
    set_osc2_level_cc,
    set_osc2_level_nrpn,
    set_osc2_octave_cc,
    set_osc2_octave_nrpn,
    set_osc2_on_nrpn,
    set_osc2_wave_high_res,
    set_osc2_wave_nrpn,
    set_osc_duo_mode_cc,
    set_osc_duo_mode_nrpn,
    set_osc_kb_reset_cc,
    set_osc_kb_reset_nrpn,
    set_sub_osc_level_cc,
    set_sub_osc_level_nrpn,
    set_sub_osc_on_nrpn,
)

# Create oscillator toolset with all tools
oscillator_toolset = FunctionToolset(
    tools=[
        set_fb_ext_on_nrpn,
        set_feedback_ext_level_cc,
        set_feedback_ext_level_nrpn,
        set_noise_level_cc,
        set_noise_level_nrpn,
        set_noise_on_nrpn,
        set_osc1_level_cc,
        set_osc1_level_nrpn,
        set_osc1_octave_cc,
        set_osc1_octave_nrpn,
        set_osc1_on_nrpn,
        set_osc1_wave_high_res,
        set_osc1_wave_nrpn,
        set_osc2_beat_freq_high_res,
        set_osc2_beat_nrpn,
        set_osc2_freq_high_res,
        set_osc2_freq_nrpn,
        set_osc2_hard_sync_cc,
        set_osc2_hard_sync_nrpn,
        set_osc2_kb_ctrl_nrpn,
        set_osc2_level_cc,
        set_osc2_level_nrpn,
        set_osc2_octave_cc,
        set_osc2_octave_nrpn,
        set_osc2_on_nrpn,
        set_osc2_wave_high_res,
        set_osc2_wave_nrpn,
        set_osc_duo_mode_cc,
        set_osc_duo_mode_nrpn,
        set_osc_kb_reset_cc,
        set_osc_kb_reset_nrpn,
        set_sub_osc_level_cc,
        set_sub_osc_level_nrpn,
        set_sub_osc_on_nrpn,
    ]
)


# Keywords that suggest using oscillator tools
OSCILLATOR_KEYWORDS = {
    'oscillator',
    'osc',
    'wave',
    'waveform',
    'sawtooth',
    'saw',
    'triangle',
    'tri',
    'square',
    'pulse',
    'noise',
    'sub',
    'sub osc',
    'octave',
    'pitch',
    'tune',
    'tuning',
    'sync',
    'hard sync',
    'feedback',
    'external',
    'detune',
    'beat',
    'frequency',
    'fundamental',
    'harmonic',
    'timbre',
    'tone',
    'sound source',
}
