# Filter tools
# Amp and FX tools
from synthgenie.synthesizers.digitone.tools.amp_fx_tool import (
    set_amp_attack,
    set_amp_decay,
    set_amp_envelope_mode,
    set_amp_envelope_reset,
    set_amp_hold,
    set_amp_pan,
    set_amp_release,
    set_amp_sustain,
    set_amp_volume,
    set_fx_bit_reduction,
    set_fx_chorus,
    set_fx_delay,
    set_fx_overdrive,
    set_fx_overdrive_routing,
    set_fx_reverb,
    set_fx_sample_rate_reduction,
    set_fx_sample_rate_routing,
)

# Euclidean sequencer tools
from synthgenie.synthesizers.digitone.tools.euclidean_tool import (
    set_euclidean_boolean_operator,
    set_euclidean_mode,
    set_euclidean_pulse_gen1,
    set_euclidean_pulse_gen2,
    set_euclidean_rotation_gen1,
    set_euclidean_rotation_gen2,
    set_euclidean_track_rotation,
)
from synthgenie.synthesizers.digitone.tools.filter_tool import (
    set_multi_mode_filter_attack,
    set_multi_mode_filter_base,
    set_multi_mode_filter_decay,
    set_multi_mode_filter_envelope_delay,
    set_multi_mode_filter_envelope_depth,
    set_multi_mode_filter_envelope_reset,
    set_multi_mode_filter_frequency,
    set_multi_mode_filter_key_tracking,
    set_multi_mode_filter_release,
    set_multi_mode_filter_resonance,
    set_multi_mode_filter_sustain,
    set_multi_mode_filter_type,
    set_multi_mode_filter_width,
)

# FM Drum machine tools
from synthgenie.synthesizers.digitone.tools.fm_drum_tool import (
    set_fm_drum_algorithm,
    set_fm_drum_body_decay,
    set_fm_drum_body_hold,
    set_fm_drum_body_level,
    set_fm_drum_decay1,
    set_fm_drum_decay2,
    set_fm_drum_end1,
    set_fm_drum_end2,
    set_fm_drum_feedback,
    set_fm_drum_fold,
    set_fm_drum_mod1,
    set_fm_drum_mod2,
    set_fm_drum_noise_base,
    set_fm_drum_noise_decay,
    set_fm_drum_noise_grain,
    set_fm_drum_noise_hold,
    set_fm_drum_noise_level,
    set_fm_drum_noise_reset,
    set_fm_drum_noise_ring_mod,
    set_fm_drum_noise_width,
    set_fm_drum_op_ab_wave,
    set_fm_drum_op_c_phase,
    set_fm_drum_op_c_wave,
    set_fm_drum_ratio1,
    set_fm_drum_ratio2,
    set_fm_drum_sweep_depth,
    set_fm_drum_sweep_time,
    set_fm_drum_transient,
    set_fm_drum_transient_level,
    set_fm_drum_tune,
)

# FM Tone machine tools
from synthgenie.synthesizers.digitone.tools.fm_tone_tool import (
    set_fm_tone_a_attack,
    set_fm_tone_a_decay,
    set_fm_tone_a_delay,
    set_fm_tone_a_end,
    set_fm_tone_a_key_track,
    set_fm_tone_a_level,
    set_fm_tone_a_ratio,
    set_fm_tone_a_ratio_offset,
    set_fm_tone_a_reset,
    set_fm_tone_a_trigger,
    set_fm_tone_algorithm,
    set_fm_tone_b1_key_track,
    set_fm_tone_b1_ratio_offset,
    set_fm_tone_b2_key_track,
    set_fm_tone_b2_ratio_offset,
    set_fm_tone_b_attack,
    set_fm_tone_b_decay,
    set_fm_tone_b_delay,
    set_fm_tone_b_end,
    set_fm_tone_b_level,
    set_fm_tone_b_ratio,
    set_fm_tone_b_reset,
    set_fm_tone_b_trigger,
    set_fm_tone_c_ratio,
    set_fm_tone_c_ratio_offset,
    set_fm_tone_detune,
    set_fm_tone_feedback,
    set_fm_tone_harmonics,
    set_fm_tone_mix,
    set_fm_tone_phase_reset,
)

# LFO tools
from synthgenie.synthesizers.digitone.tools.lfo_tool import (
    set_lfo1_depth,
    set_lfo1_destination,
    set_lfo1_fade,
    set_lfo1_multiplier,
    set_lfo1_speed,
    set_lfo1_start_phase,
    set_lfo1_trigger_mode,
    set_lfo1_waveform,
    set_lfo2_depth,
    set_lfo2_destination,
    set_lfo2_fade,
    set_lfo2_multiplier,
    set_lfo2_speed,
    set_lfo2_start_phase,
    set_lfo2_trigger_mode,
    set_lfo2_waveform,
    set_lfo3_depth,
    set_lfo3_destination,
    set_lfo3_fade,
    set_lfo3_multiplier,
    set_lfo3_speed,
    set_lfo3_start_phase,
    set_lfo3_trigger_mode,
    set_lfo3_waveform,
)

# Miscellaneous tools
from synthgenie.synthesizers.digitone.tools.misc_tool import set_master_overdrive, set_pattern_mute

# Mixer and compressor tools
from synthgenie.synthesizers.digitone.tools.mixer_tool import (
    set_compressor_attack_time,
    set_compressor_dry_wet_mix,
    set_compressor_makeup_gain,
    set_compressor_ratio,
    set_compressor_release_time,
    set_compressor_sidechain_filter,
    set_compressor_sidechain_source,
    set_compressor_threshold,
    set_external_input_dual_mono,
    set_external_input_l_chorus_send,
    set_external_input_l_delay_send,
    set_external_input_l_level,
    set_external_input_l_pan,
    set_external_input_l_reverb_send,
    set_external_input_r_chorus_send,
    set_external_input_r_delay_send,
    set_external_input_r_level,
    set_external_input_r_pan,
    set_external_input_r_reverb_send,
    set_pattern_volume,
)

# Send FX tools (global effects)
from synthgenie.synthesizers.digitone.tools.send_fx_tool import (
    set_chorus_delay_send,
    set_chorus_depth,
    set_chorus_highpass_filter,
    set_chorus_mix_volume,
    set_chorus_reverb_send,
    set_chorus_speed,
    set_chorus_width,
    set_delay_feedback,
    set_delay_highpass_filter,
    set_delay_lowpass_filter,
    set_delay_mix_volume,
    set_delay_pingpong,
    set_delay_reverb_send,
    set_delay_stereo_width,
    set_delay_time,
    set_reverb_decay_time,
    set_reverb_highpass_filter,
    set_reverb_lowpass_filter,
    set_reverb_mix_volume,
    set_reverb_predelay,
    set_reverb_shelving_freq,
    set_reverb_shelving_gain,
)

# Swarmer machine tools
from synthgenie.synthesizers.digitone.tools.swarmer_tool import (
    set_swarmer_animation,
    set_swarmer_detune,
    set_swarmer_main,
    set_swarmer_main_octave,
    set_swarmer_mix,
    set_swarmer_noise_mod,
    set_swarmer_swarm,
    set_swarmer_tune,
)

# Track tools
from synthgenie.synthesizers.digitone.tools.track_tool import set_track_level, set_track_mute

# Trig tools
from synthgenie.synthesizers.digitone.tools.trig_tool import (
    set_filter_trig,
    set_lfo_trig,
    set_portamento_on_off,
    set_portamento_time,
    set_trig_length,
    set_trig_note,
    set_trig_velocity,
)

# Wavetone machine tools
from synthgenie.synthesizers.digitone.tools.wavetone_tool import (
    set_wavetone_attack,
    set_wavetone_decay,
    set_wavetone_drift,
    set_wavetone_hold,
    set_wavetone_mod_type,
    set_wavetone_noise_base,
    set_wavetone_noise_character,
    set_wavetone_noise_level,
    set_wavetone_noise_type,
    set_wavetone_noise_width,
    set_wavetone_osc1_level,
    set_wavetone_osc1_offset,
    set_wavetone_osc1_phase_distortion,
    set_wavetone_osc1_pitch,
    set_wavetone_osc1_table,
    set_wavetone_osc1_waveform,
    set_wavetone_osc2_level,
    set_wavetone_osc2_offset,
    set_wavetone_osc2_phase_distortion,
    set_wavetone_osc2_pitch,
    set_wavetone_osc2_table,
    set_wavetone_osc2_waveform,
    set_wavetone_reset_mode,
)

__all__ = [
    # Filter
    'set_multi_mode_filter_attack',
    'set_multi_mode_filter_base',
    'set_multi_mode_filter_decay',
    'set_multi_mode_filter_envelope_delay',
    'set_multi_mode_filter_envelope_depth',
    'set_multi_mode_filter_envelope_reset',
    'set_multi_mode_filter_frequency',
    'set_multi_mode_filter_key_tracking',
    'set_multi_mode_filter_release',
    'set_multi_mode_filter_resonance',
    'set_multi_mode_filter_sustain',
    'set_multi_mode_filter_type',
    'set_multi_mode_filter_width',
    # Amp and FX
    'set_amp_attack',
    'set_amp_decay',
    'set_amp_envelope_mode',
    'set_amp_envelope_reset',
    'set_amp_hold',
    'set_amp_pan',
    'set_amp_release',
    'set_amp_sustain',
    'set_amp_volume',
    'set_fx_bit_reduction',
    'set_fx_chorus',
    'set_fx_delay',
    'set_fx_overdrive',
    'set_fx_overdrive_routing',
    'set_fx_reverb',
    'set_fx_sample_rate_reduction',
    'set_fx_sample_rate_routing',
    # LFO
    'set_lfo1_depth',
    'set_lfo1_destination',
    'set_lfo1_fade',
    'set_lfo1_multiplier',
    'set_lfo1_speed',
    'set_lfo1_start_phase',
    'set_lfo1_trigger_mode',
    'set_lfo1_waveform',
    'set_lfo2_depth',
    'set_lfo2_destination',
    'set_lfo2_fade',
    'set_lfo2_multiplier',
    'set_lfo2_speed',
    'set_lfo2_start_phase',
    'set_lfo2_trigger_mode',
    'set_lfo2_waveform',
    'set_lfo3_depth',
    'set_lfo3_destination',
    'set_lfo3_fade',
    'set_lfo3_multiplier',
    'set_lfo3_speed',
    'set_lfo3_start_phase',
    'set_lfo3_trigger_mode',
    'set_lfo3_waveform',
    # Track
    'set_track_level',
    'set_track_mute',
    # Trig
    'set_filter_trig',
    'set_lfo_trig',
    'set_portamento_on_off',
    'set_portamento_time',
    'set_trig_length',
    'set_trig_note',
    'set_trig_velocity',
    # Euclidean
    'set_euclidean_boolean_operator',
    'set_euclidean_mode',
    'set_euclidean_pulse_gen1',
    'set_euclidean_pulse_gen2',
    'set_euclidean_rotation_gen1',
    'set_euclidean_rotation_gen2',
    'set_euclidean_track_rotation',
    # Send FX
    'set_chorus_delay_send',
    'set_chorus_depth',
    'set_chorus_highpass_filter',
    'set_chorus_mix_volume',
    'set_chorus_reverb_send',
    'set_chorus_speed',
    'set_chorus_width',
    'set_delay_feedback',
    'set_delay_highpass_filter',
    'set_delay_lowpass_filter',
    'set_delay_mix_volume',
    'set_delay_pingpong',
    'set_delay_reverb_send',
    'set_delay_stereo_width',
    'set_delay_time',
    'set_reverb_decay_time',
    'set_reverb_highpass_filter',
    'set_reverb_lowpass_filter',
    'set_reverb_mix_volume',
    'set_reverb_predelay',
    'set_reverb_shelving_freq',
    'set_reverb_shelving_gain',
    # Mixer
    'set_compressor_attack_time',
    'set_compressor_dry_wet_mix',
    'set_compressor_makeup_gain',
    'set_compressor_ratio',
    'set_compressor_release_time',
    'set_compressor_sidechain_filter',
    'set_compressor_sidechain_source',
    'set_compressor_threshold',
    'set_external_input_dual_mono',
    'set_external_input_l_chorus_send',
    'set_external_input_l_delay_send',
    'set_external_input_l_level',
    'set_external_input_l_pan',
    'set_external_input_l_reverb_send',
    'set_external_input_r_chorus_send',
    'set_external_input_r_delay_send',
    'set_external_input_r_level',
    'set_external_input_r_pan',
    'set_external_input_r_reverb_send',
    'set_pattern_volume',
    # Misc
    'set_master_overdrive',
    'set_pattern_mute',
    # FM Tone
    'set_fm_tone_a_attack',
    'set_fm_tone_a_decay',
    'set_fm_tone_a_delay',
    'set_fm_tone_a_end',
    'set_fm_tone_a_key_track',
    'set_fm_tone_a_level',
    'set_fm_tone_a_ratio',
    'set_fm_tone_a_ratio_offset',
    'set_fm_tone_a_reset',
    'set_fm_tone_a_trigger',
    'set_fm_tone_algorithm',
    'set_fm_tone_b1_key_track',
    'set_fm_tone_b1_ratio_offset',
    'set_fm_tone_b2_key_track',
    'set_fm_tone_b2_ratio_offset',
    'set_fm_tone_b_attack',
    'set_fm_tone_b_decay',
    'set_fm_tone_b_delay',
    'set_fm_tone_b_end',
    'set_fm_tone_b_level',
    'set_fm_tone_b_ratio',
    'set_fm_tone_b_reset',
    'set_fm_tone_b_trigger',
    'set_fm_tone_c_ratio',
    'set_fm_tone_c_ratio_offset',
    'set_fm_tone_detune',
    'set_fm_tone_feedback',
    'set_fm_tone_harmonics',
    'set_fm_tone_mix',
    'set_fm_tone_phase_reset',
    # FM Drum
    'set_fm_drum_algorithm',
    'set_fm_drum_body_decay',
    'set_fm_drum_body_hold',
    'set_fm_drum_body_level',
    'set_fm_drum_decay1',
    'set_fm_drum_decay2',
    'set_fm_drum_end1',
    'set_fm_drum_end2',
    'set_fm_drum_feedback',
    'set_fm_drum_fold',
    'set_fm_drum_mod1',
    'set_fm_drum_mod2',
    'set_fm_drum_noise_base',
    'set_fm_drum_noise_decay',
    'set_fm_drum_noise_grain',
    'set_fm_drum_noise_hold',
    'set_fm_drum_noise_level',
    'set_fm_drum_noise_reset',
    'set_fm_drum_noise_ring_mod',
    'set_fm_drum_noise_width',
    'set_fm_drum_op_ab_wave',
    'set_fm_drum_op_c_phase',
    'set_fm_drum_op_c_wave',
    'set_fm_drum_ratio1',
    'set_fm_drum_ratio2',
    'set_fm_drum_sweep_depth',
    'set_fm_drum_sweep_time',
    'set_fm_drum_transient',
    'set_fm_drum_transient_level',
    'set_fm_drum_tune',
    # Wavetone
    'set_wavetone_attack',
    'set_wavetone_decay',
    'set_wavetone_drift',
    'set_wavetone_hold',
    'set_wavetone_mod_type',
    'set_wavetone_noise_base',
    'set_wavetone_noise_character',
    'set_wavetone_noise_level',
    'set_wavetone_noise_type',
    'set_wavetone_noise_width',
    'set_wavetone_osc1_level',
    'set_wavetone_osc1_offset',
    'set_wavetone_osc1_phase_distortion',
    'set_wavetone_osc1_pitch',
    'set_wavetone_osc1_table',
    'set_wavetone_osc1_waveform',
    'set_wavetone_osc2_level',
    'set_wavetone_osc2_offset',
    'set_wavetone_osc2_phase_distortion',
    'set_wavetone_osc2_pitch',
    'set_wavetone_osc2_table',
    'set_wavetone_osc2_waveform',
    'set_wavetone_reset_mode',
    # Swarmer
    'set_swarmer_animation',
    'set_swarmer_detune',
    'set_swarmer_main',
    'set_swarmer_main_octave',
    'set_swarmer_mix',
    'set_swarmer_noise_mod',
    'set_swarmer_swarm',
    'set_swarmer_tune',
]
