version: '3.8'

services:
  api:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - API_ENV=${API_ENV:-development}
      - DEBUG=${DEBUG:-True}
      - SENTRY_DSN=${SENTRY_DSN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENT_MODEL=${AGENT_MODEL}
    volumes:
      - db-data:/app/synthgenie.db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/docs']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db-data:
    driver: local
